import type { ScanJob, SecurityHeadersResult } from './types';

  status: 'added' | 'removed' | 'un
}
export interface ExportData {
  scans: ScanJob[];
 

    unchanged: number;
}
const HEADER_DISPLA
  'content-security-policy': 'Con
  'x-frame
  'permissions-pol

  const lines: strin
  lines.push(`Security
  li
 

  lines.push(`Removed Headers,${data.stats.removed}`);
  lines.push(``);
  const scanHeaders = data.scans.map((scan, idx) => {
    return `Scan ${idx + 1} (${date})`;
  
  
    const displayName = HEADER_DISPLAY_NAMES[
  

    
  });
  
  downloadFile(blob, `security-headers-comparison-$

  const canvas = document.createElement('canvas');
  if (!ctx) retur
  
  canvas.width = width;

  ctx.fillRect(0, 0, width, height);
  let y = 60;
  const rightMargin = width - 60;

  
  y += 40;
  ctx.font = '16px Inter, sans-serif';
  ctx.fillText(`Target: ${data.target}`
  ctx.fillText(
  

  
  ctx.moveTo(leftMargin, y);
  ctx.stroke();

  ctx.font = 'bold 24px Inter, 
  y += 40;
  ctx.font = '18px Inter, sans-serif';
    { label: 'Add
    
  ];
  sum
  
    ctx.font = 'bold 18px Inter
    ctx.font = '18px Inter, sans-serif';
  });
 

  ctx.lineTo(rightMargin, y);
  y += 40;
  ctx.fillStyle = '#0a0a0a';
  ctx.fillText('Hea


  let itemCount = 0;
  data.comparison.forEa
      ctx.fillStyle = '#6

    }
    if (itemCount >= maxItemsPerPage

    ctx.fillS
    ctx.fillText(display

      added: '#22c55e',

    };
    ctx.fillStyle = statusColors[header.sta
    ctx.fillText(`Status: ${header.status.toUpperCase()}`, leftMargi


      const scanDate = new Date(data.s
      ctx.font = '12px Inter
      y += 20;
      ctx.
      const displayValue = value ? (value.length > 60 ? value.substring(0, 
      y +=

    ctx.st

    ctx.lineTo(rightMargin - 2
    y += 20;
    itemCount++;

  ctx.fillStyle = '#999999';
  ctx.textAlign


    }
}
function downloadFile(blob: Blob, filenam
  const li

  link.click();
  URL.revokeObjectURL(ur















































































    y += 15;
    ctx.strokeStyle = '#f0f0f0';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(leftMargin + 20, y);
    ctx.lineTo(rightMargin - 20, y);
    ctx.stroke();
    y += 20;

    itemCount++;
  });

  y = height - 60;
  ctx.fillStyle = '#999999';
  ctx.font = '12px Inter, sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText('Generated by Security Toolkit', width / 2, y);

  canvas.toBlob(blob => {
    if (blob) {
      downloadFile(blob, `security-headers-comparison-${data.target}-${Date.now()}.png`);
    }
  }, 'image/png');
}

function downloadFile(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
